### ISSUE TITLE
Odd repeat of Loops & Odd public API of Page class

### ISSUE THREAD

**Issue by Rossgath** [mattyoungberg/IdahoStatesmanDeliveryBoy#1]
https://github.com/mattyoungberg/IdahoStatesmanDeliveryBoy/blob/4c70601f803f557a779047fd0be5dd94d76aed3e/src/main/java/Main.java#L68

There may be a good reason for this (?), but it is very odd to see us loop over the same list of pages 3 times. Is there a reason we can't loop once and do the 3 pieces per loop? Do we have to request all of the web pages first, then all of the PDFs, etc?

Along those lines, though: It may make more sense to capture more of this "behinds the scenes how it works" within the Page class. It's very odd to see a method that'll throw an error if you didn't call another method first, as it means the use of that class is more complicated than you'd really want. Suggestions with this:

Minor: Rename "Page" to "PageRequestor" -> It's an object that makes WS requests to get page information. Consider having two classes, one "Data" type object (Page) that has the data, and one "PageRequestor" which gets the Page information. In general, I wouldn't expect/want a PageRequestor to have to keep track of some of the state that it does (ie: whether another method has been called or not).
Major: For the public methods: Combine the three methods being called in Main into just one. Make the public API as clear and dummy-proof as possible. Having the small methods within Page is excellent, though, but they don't all need to be exposed. Make those private, and think about what the real "from the outside" goal of the class is, and make an API that crisply does that.

**Comment by mattyoungberg** [comment]
> Do we have to request all of the web pages first, then all of the PDFs, etc?

Yes. Behind the scenes, asynchronous web requests are taking place and are all returning `CompletableFuture<>` objects. When the second loop starts, the `.join()` method on that object is being called first, but since many other operations have taken place before then, chances of the thread being done are much higher and it can just continue processing. If not, the iterations in front of it simply get more time to complete so when processing resumes, chances are even higher that they're done than before.

If I put it all on one loop, each step would, in effect, be synchronous and we'd loose the speed that's gained by the ability to continue processing other threads while we wait for the previously started ones to finish.

I tried to use a `Stream` solution for those three loops, but for some reason that I don't quite understand, performance took a significant hit. I'm not sure how streams are processed under the hood, but it wasn't working nearly as quickly, so I went back to the loops.

But to your point, I'm very convinced that these different requests need to be put into separate objects. The way it's laid out now, it breaks the whole "an object does one thing" mentality.

There's an HTML file that needs to be requested first, parsed, and only then can I actually request the PDF. So, moving forward, I'll refactor the `Page` object into two: a `PageHTMLRequestor` and `PagePDFRequestor`. The latter can return the PDF as a byte array. At that point, do you think it's worth having a `Page` object if really all it'd serve is to return a byte array? It seems to be in the purview of the `PagePDFRequestor` class.

**Comment by mattyoungberg** [comment]
@Rossgath, I incorporated your structural comments into the project. Tell me what you think.

>It's very odd to see a method that'll throw an error if you didn't call another method first, as it means the use of that class is more complicated than you'd really want.

> Minor: Rename "Page" to "PageRequestor" -> It's an object that makes WS requests to get page information. Consider having two classes, one "Data" type object (Page) that has the data, and one "PageRequestor" which gets the Page information. In general, I wouldn't expect/want a PageRequestor to have to keep track of some of the state that it does (ie: whether another method has been called or not).

I took the "Requestor" purpose and naming convention to heart and broke those out into classes. Since `CompletableFuture`s are really just threads under the hood, I tried to mimic a thread interface by including `.start()` and `.join()` methods in both. Hopefully that will keep things nicely relatable and semantic for anybody who wonders why I'm doing multiple loops.

> Major: For the public methods: Combine the three methods being called in Main into just one. Make the public API as clear and dummy-proof as possible. Having the small methods within Page is excellent, though, but they don't all need to be exposed. Make those private, and think about what the real "from the outside" goal of the class is, and make an API that crisply does that.

For this, I refactored all the options handling (which severely bloated the class) into `RuntimeOptions`. That makes `Main` about the actual program execution. Given the refactor, I'm hoping it reads more succinctly now. Even though the method runs 31 lines, it's all at the same exact level of abstraction (In my humble and perhaps uninformed opinion). That, in addition to the options being refactored out, makes it appear to me that it should all be there. But please disagree if you do.
